version: '3'
services:
  blaze-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 3030:3030
  blaze-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        TORRENT_SIZE_LIMIT: 300000000000
        WS_SIZE_LIMIT: 100000000
        SERVER_HOST: 0.0.0.0
        WS_HOST: 0.0.0.0
    ports:
      - 80:80
    depends_on:
      - blaze-server
    volumes:
      - ./nginx/compose-nginx.conf:/etc/nginx/nginx.conf
